Delete $:literal codepath
It turns out this breaks non-builtin literal suffixes, such as in
`quote!(1u256)`. Those match fine against $:tt, but if you match them
against $:literal they eagerly fail the macro expansion without falling
through to the next macro_rules arm.

    error: invalid width `256` for integer literal
     --> repro.rs:4:9
      |
    4 |         1u256
      |         ^^^^^
      |
      = help: valid widths are 8, 16, 32, 64 and 128